name: CI/CD Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t fiappostech-desafio2-marketplace-auth:latest -f ./src/auth/Dockerfile .

    - name: Tag Docker image
      run: |
        docker tag fiappostech-desafio2-marketplace-auth:latest ${{ secrets.DOCKER_USERNAME }}/fiappostech-desafio2-marketplace-auth:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/fiappostech-desafio2-marketplace-auth:latest

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 -p 8081:8081 --name auth-app-container ${{ secrets.DOCKER_USERNAME }}/fiappostech-desafio2-marketplace-auth:latest

    - name: Verify Docker container is running
      run: |
        docker ps -a
